import type { Metadata } from "next";
import "./globals.css";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/elements/Sidebar";
import Navbar from "@/components/elements/Navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SidebarProvider } from "@/context/SidebarContext";
import { Toaster } from "sonner";
import { AuthListener } from "@/components/elements/AuthListener";
import SessionProvider from "@/components/providers/session-provider";
import ReactQueryProvider from "@/components/providers/react-query";

export const metadata: Metadata = {
  title: {
    default: "Absensi App",
    template: "%s | Absensi",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("relative antialiased", fontSans.className)}>
        <ReactQueryProvider>
          <SessionProvider>
            <AuthListener />
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SidebarProvider>
                <Sidebar />
                <Navbar />
                {children}
              </SidebarProvider>
            </ThemeProvider>
            <Toaster richColors />
          </SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
